run:
  skip-dirs-use-default: false
linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^print$'
      - '^println$'
      - '^panic$'
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  varnamelen:
      ignore-decls:
      - i int
      - t *console.TB
      - t crosstesting.TB
      - t testing.TB
linters:
  enable-all: true
  disable:
    - cyclop           # covered by gocyclo
    - exhaustivestruct # zero values in tests are okay
    - funlen           # rely on code review to limit function length
    - gocognit         # dubious "cognitive overhead" quantification
    - gofumpt          # prefer standard gofmt
    - golint           # deprecated by Go team
    - gomnd            # some unnamed constants are okay
    - interfacer       # deprecated by author
    - ireturn          # "accept interfaces, return structs" isn't ironclad
    - lll              # don't want hard limits for line length
    - maintidx         # covered by gocyclo
    - maligned         # readability trumps efficient struct packing
    - nlreturn         # generous whitespace violates house style
    - scopelint        # deprecated by author
    - testpackage      # internal tests are fine
    - wrapcheck        # don't _always_ need to wrap errors
    - wsl              # generous whitespace violates house style
issues:
  exclude:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - "err113: do not define dynamic errors.*"
  exclude-rules:
    # We need to init some globals to use in tests.
    - linters: [gochecknoglobals]
      path: internal/interop/grpc/test_cases.go
    # We need to init some globals to use in tests.
    - linters: [gochecknoglobals]
      path: internal/interop/connect/test_cases.go
    # This is a false positive as the fatal will not occur together with an `gconn`.
    - linters: [gocritic]
      path: cmd/client/main.go
      text: "exitAfterDefer: log.Fatalf will exit"
    # We force the test server to exit if there is an error when shutting down the server.
    - linters: [gocritic]
      path: cmd/server/serverconnect/main.go
      text: "exitAfterDefer: log.Fatalln will exit"
    # This is a false positive as an issue of gci https://github.com/daixiang0/gci/issues/60.
    - linters: [gci]
      path: internal/interop/grpc/test_cases.go
      text: "Expected 't', Found '\"'"
    # This is a false positive as an issue of gci https://github.com/daixiang0/gci/issues/60.
    - linters: [gci]
      path: internal/interop/connect/test_cases.go
      text: "Expected 'c', Found '\"'"
