version: "3.9"
services:
  server-connect:
    build:
      context: .
      dockerfile: Dockerfile.crosstest
    entrypoint: /usr/local/bin/serverconnect --h1port "8080" --h2port "8081"
    expose:
      - "8080"
      - "8081"
  server-grpc:
    build:
      context: .
      dockerfile: Dockerfile.crosstest
    entrypoint: /usr/local/bin/servergrpc --port "8082"
    expose:
      - "8082"
  envoy:
    image: envoyproxy/envoy:v1.20-latest
    ports:
      - "9091:9091"
      - "9092:9092"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
  client-connect-to-connect:
    build:
      context: .
      dockerfile: Dockerfile.crosstest
    entrypoint: /usr/local/bin/client --host="server-connect" --port="8081" --implementation="connect"
    depends_on:
      - server-connect
  client-connect-to-grpc:
    build:
      context: .
      dockerfile: Dockerfile.crosstest
    entrypoint: /usr/local/bin/client --host="server-grpc" --port="8082" --implementation="connect"
    depends_on:
      - server-grpc
  client-grpc-to-connect:
    build:
      context: .
      dockerfile: Dockerfile.crosstest
    entrypoint: /usr/local/bin/client --host="server-connect" --port="8081" --implementation="grpc-go"
    depends_on:
      - server-connect
  client-grpc-to-grpc:
    build:
      context: .
      dockerfile: Dockerfile.crosstest
    entrypoint: /usr/local/bin/client --host="server-grpc" --port="8082" --implementation="grpc-go"
    depends_on:
      - server-grpc
  client-grpc-web-to-connect-h1:
    build:
      context: .
      dockerfile: Dockerfile.crosstestweb
    entrypoint: npm run test -- --host="server-connect" --port="8080"
    depends_on:
      - server-connect
  client-grpc-web-to-envoy-connect:
    build:
      context: .
      dockerfile: Dockerfile.crosstestweb
    entrypoint: npm run test -- --host="envoy" --port="9091"
    depends_on:
      - server-connect
      - envoy
  client-grpc-web-to-envoy-grpc:
    build:
      context: .
      dockerfile: Dockerfile.crosstestweb
    entrypoint: npm run test -- --host="envoy" --port="9092"
    depends_on:
      - server-grpc
      - envoy
