name: crosstest
on:
  schedule:
    - cron: 0 15 * * * # Runs 15:00 UTC, 11:00 Eastern
  workflow_dispatch: {} # support manual runs
permissions: read-all
jobs:
  connect-go-crosstest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      # TODO: Remove when connect-web is public.
      - name: Configure Private Repo Access
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.CONNECT_WEB_DEPLOY_KEY }}
            ${{ secrets.PROTOBUF_ES_DEPLOY_KEY }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-connect-crosstest-ci-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-connect-crosstest-ci-
          # upgrades all dependencies to latest version
      - name: Upgrade and Test
        run: make upgrade && make test
        env:
          GOPRIVATE: github.com/bufbuild
