name: crosstest
on:
  schedule:
    - cron: 10 15 * * * # Runs 00:10 UTC, 20:10 Eastern
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
  issues: write
jobs:
  connect-go-crosstest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      # TODO: Remove when connect-web is public.
      - name: Configure Private Repo Access
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.CONNECT_WEB_DEPLOY_KEY }}
            ${{ secrets.PROTOBUF_ES_DEPLOY_KEY }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-connect-crosstest-ci-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-connect-crosstest-ci-
          # upgrades all dependencies to latest version
      - name: Upgrade and Test
        # we don't need the soak tests for this job, we only need the base interop functionality
        run: make upgrade && make shorttest
        env:
          GOPRIVATE: github.com/bufbuild
      - name: Open Issue on Fail
        uses: dblock/create-a-github-issue@v3
        if: failure()
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          filename: .github/crosstest-issue-template.md
          update_existing: true
          search_existing: open
